config/routes.rb
Datetracker::Application.routes.draw do
  match '/:locale' => 'importantdates#index'
  scope "/:locale", :locale => /en|fr/ do
    resources :importantdates
  end

end

app/models/importantdate.rb
class Importantdate < ActiveRecord::Base
  attr_accessible :description, :importantdate, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  # app/controllers/application_controller.rb
  before_filter :set_locale
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end


end

app/controllers/importantdates_controller.rb
class ImportantdatesController < ApplicationController
	def index
		@importantdates = Importantdate.where("importantdate >= (?)", Date.today).order("importantdate asc")
	end
	def new
		@importantdates = Importantdate.new
	end
	def create
		@importantdate = Importantdate.new(params[:importantdate])
  		if @importantdate.save
  		  flash[:notice] = t(:date_added)
  		  redirect_to @importantdate
  	    else
  	      flash[:notice] = "Did not save"
  	      redirect_to @importantdate
  	    end
	end
	def show
      @importantdate = Importantdate.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/importantdates_helper.rb
module ImportantdatesHelper
end

app/views/importantdates/index.html.erb
<p>
<%= link_to_unless I18n.locale == :en, "English", locale:  :en %>
|
<%= link_to_unless I18n.locale == :fr, "Français", locale:  :fr %>
</p>
<h2><%= I18n.t(:date_header) %></h2>
<ul>
	<% @importantdates.each do |importantdate| %>
	  <li><%=  I18n.localize(importantdate.importantdate, format: :long) %> - <%= importantdate.name %></li>
	<% end %>
</ul>
<%= link_to I18n.t(:add_date), new_importantdate_path %>

app/views/importantdates/new.html.erb
<h2><% I18n.t(:new_date) %></h2>
<%= form_for(@importantdates) do |f| %>
	<p>
	  <%= f.label I18n.t(:importantdate) %><br />
	  <%= f.date_select :importantdate %>
	</p>

	<p>
	  <%= f.label I18n.t(:name) %><br />
	  <%= f.text_field :name %>
	</p>
	<p>
	  <%= f.label I18n.t(:description) %><br />
	  <%= f.text_area :description %>
	</p>
	<%= f.submit %>
<% end %>

app/views/importantdates/show.html.erb
<h2><%= @importantdate.name %></h2>
<p><%= @importantdate.importantdate %></p>
<p><%= @importantdate.description %></p>>

<%= link_to I18n.t(:back_link), importantdates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Datetracker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
  	 <%= value %>
  </div>
<% end %>

<%= yield %>

</body>
</html>